package BhtMimMindMap.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BHTMainTopic = 0;
  public static final int BHTMarker = 1;
  public static final int BHTMindMap = 2;
  public static final int BHTRootTopic = 3;
  public static final int BHTSubTopic = 4;
  public static final int BHTTopic = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5b38a289a18d48cfL, 0xa3c27f325ec8d2f5L);
    builder.put(0x792954c5a407f877L, BHTMainTopic);
    builder.put(0x792954c5a406c44fL, BHTMarker);
    builder.put(0x792954c5a4066e3eL, BHTMindMap);
    builder.put(0x792954c5a40781c4L, BHTRootTopic);
    builder.put(0x792954c5a4083e47L, BHTSubTopic);
    builder.put(0x792954c5a40696b1L, BHTTopic);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
