package BHTMindMap.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new BHTMainIdea_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new BHTMindMap_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new BHTRootIdea_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new BHTSubIdea_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df790f61L), MetaIdFactory.conceptId(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df788159L), MetaIdFactory.conceptId(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df78d6c9L), MetaIdFactory.conceptId(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df78f2a1L)).seal();
}
