package BHTMindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class BHTMindMap_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("\\documentclass{article}");
    tgs.newLine();
    tgs.append("\\usepackage[utf8]{inputenc}");
    tgs.newLine();
    tgs.append("\\title{Einsendeaufgabe 9 – DSL}");
    tgs.newLine();
    tgs.append("\\author{Jana Deutschlaender}");
    tgs.newLine();
    tgs.append("\\date{February 2023}");
    tgs.newLine();
    tgs.append("\\begin{document}");
    tgs.newLine();
    tgs.append("\\maketitle");
    tgs.newLine();
    tgs.append("\\paragraph{");
    tgs.append("Die folgende Struktur wurde aus einer Mindmap der Sprache \\emph{BHTMindMap} erstellt:");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append("(");
    tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rootIdea$MLrr), PROPS.name$MnvL));
    tgs.append(")");
    tgs.append("}");
    tgs.newLine();
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.rootIdea$MLrr));
    tgs.append("\\end{document}");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink rootIdea$MLrr = MetaAdapterFactory.getContainmentLink(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df788159L, 0xa09fe14df798e66L, "rootIdea");
  }
}
