package BHTMindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class BHTSubIdea_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(ctx.getPrimaryInput()), CONCEPTS.BHTSubIdea$Lw)) {
      if (SNodeOperations.isInstanceOf(SNodeOperations.getParent(SNodeOperations.getParent(ctx.getPrimaryInput())), CONCEPTS.BHTSubIdea$Lw)) {
        tgs.append("\\paragraph{");
        tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
      } else {
        tgs.append("\\subsubsection{");
        tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
      }
    } else {
      tgs.append("\\subsection{");
      tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    }
    tgs.append("}");
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.subSubIdea$VYdC)) {
      tgs.appendNode(item);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BHTSubIdea$Lw = MetaAdapterFactory.getConcept(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df78f2a1L, "BHTMindMap.structure.BHTSubIdea");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink subSubIdea$VYdC = MetaAdapterFactory.getContainmentLink(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df78f2a1L, 0xa09fe14df79b1dfL, "subSubIdea");
  }
}
