package BHTMindMap.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import BHTMindMap.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.BHTMainIdea:
        return new BHTMainIdea_TextGen();
      case LanguageConceptSwitch.BHTMindMap:
        return new BHTMindMap_TextGen();
      case LanguageConceptSwitch.BHTRootIdea:
        return new BHTRootIdea_TextGen();
      case LanguageConceptSwitch.BHTSubIdea:
        return new BHTSubIdea_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.BHTMindMap$jT)) {
        String fname = getFileName_BHTMindMap(root);
        String ext = getFileExtension_BHTMindMap(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_BHTMindMap(SNode node) {
    return "mm__" + SPropertyOperations.getString(node, PROPS.name$MnvL);
  }
  private static String getFileExtension_BHTMindMap(SNode node) {
    return "tex";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BHTMindMap$jT = MetaAdapterFactory.getConcept(0xbbb766b466e54907L, 0xa8925f51afe0212dL, 0xa09fe14df788159L, "BHTMindMap.structure.BHTMindMap");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }
}
