# Test action for esa 8
# prompts a hello world message and two other lines
name: firstWorkflow

on: push

jobs:
  job1:
    name: firstJob
    runs-on: ubuntu-latest
    steps:
      - name: firstStep
        uses: actions/checkout@v3
      - name: secondStep
        run: env | sort
  job2:
    name: secondJob
    runs-on: windows-latest
    steps:
      - name: firstStep
        uses: actions/checkout@v3
      - name: secondStep
        run: "Get-ChildItem Env: | Sort-Object Name"
