package BHTMindMap.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BHTIdea = 0;
  public static final int BHTLabel = 1;
  public static final int BHTMainIdea = 2;
  public static final int BHTMindMap = 3;
  public static final int BHTRootIdea = 4;
  public static final int BHTSubIdea = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xbbb766b466e54907L, 0xa8925f51afe0212dL);
    builder.put(0xa09fe14df78a584L, BHTIdea);
    builder.put(0xa09fe14df792c06L, BHTLabel);
    builder.put(0xa09fe14df790f61L, BHTMainIdea);
    builder.put(0xa09fe14df788159L, BHTMindMap);
    builder.put(0xa09fe14df78d6c9L, BHTRootIdea);
    builder.put(0xa09fe14df78f2a1L, BHTSubIdea);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
